# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PrintYour3D
                                 A QGIS plugin
 With this plugin you could print 3D model from your data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-28
        copyright            : (C) 2020 by Szymek Ślęczka
        email                : szymex23@o2.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PrintYour3D class from file PrintYour3D.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Print_Your_3D import PrintYour3D
    return PrintYour3D(iface)
